# Generated by Django 4.2.17 on 2025-01-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0002_alter_eventbooking_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["date", "time"]},
        ),
        migrations.AddField(
            model_name="reservation",
            name="arrival_status",
            field=models.CharField(
                choices=[
                    ("not_arrived", "Not Arrived"),
                    ("seated", "Seated"),
                    ("no_show", "No Show"),
                ],
                default="not_arrived",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="is_manual_entry",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
