# Generated by Django 4.2.17 on 2025-01-08 01:18

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0003_transaction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="date",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("stripe", "Credit Card"),
                    ("apple_pay", "Apple Pay"),
                    ("paypal", "PayPal"),
                    ("in_store", "Pay at Pickup"),
                ],
                default="in_store",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="refund_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="refunded_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="refunded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refunds_processed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="reference_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("refunded", "Refunded"),
                    ("failed", "Failed"),
                    ("pending", "Pending"),
                ],
                default="completed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
