# Generated by Django 4.2.17 on 2025-01-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_transaction_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("order", "Order Payment"),
                    ("refund", "Refund"),
                    ("giftcard_purchase", "Gift Card Purchase"),
                    ("giftcard_redemption", "Gift Card Redemption"),
                ],
                max_length=50,
            ),
        ),
    ]
