# Generated by Django 4.2.17 on 2024-12-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["display_order", "name"],
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="display_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="ingredients",
            field=models.TextField(
                blank=True, help_text="Enter the ingredients used in this dish"
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="spice_level",
            field=models.CharField(
                choices=[
                    ("mild", "Mild"),
                    ("medium", "Medium"),
                    ("spicy", "Spicy"),
                    ("very_spicy", "Very Spicy"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="menu_items/"),
        ),
    ]
