# Generated by Django 4.2.17 on 2025-01-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_alter_category_options_category_display_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemAddon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ItemChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "price_adjustment",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="menuitem",
            name="has_choices",
            field=models.BooleanField(
                default=False,
                help_text="Item has different choices (e.g., Veg/Non-veg)",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="has_spice_customization",
            field=models.BooleanField(
                default=False, help_text="Allow customers to customize spice level"
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="requires_choice",
            field=models.BooleanField(
                default=False, help_text="Customer must select a choice"
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="spice_level",
            field=models.CharField(
                choices=[
                    ("none", "No Spice"),
                    ("mild", "Mild"),
                    ("medium", "Medium"),
                    ("spicy", "Spicy"),
                    ("very_spicy", "Very Spicy"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="available_addons",
            field=models.ManyToManyField(blank=True, to="menu.itemaddon"),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="available_choices",
            field=models.ManyToManyField(blank=True, to="menu.itemchoice"),
        ),
    ]
