# Generated by Django 4.2.17 on 2025-01-21 06:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0003_itemaddon_itemchoice_menuitem_has_choices_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="categories/"),
        ),
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="itemaddon",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="itemaddon",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="itemchoice",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="itemchoice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="allergens",
            field=models.TextField(blank=True, help_text="List potential allergens"),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="calories",
            field=models.PositiveIntegerField(
                blank=True, help_text="Calories per serving", null=True
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_gluten_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_vegan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_vegetarian",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="preparation_time",
            field=models.PositiveIntegerField(
                default=15, help_text="Average preparation time in minutes"
            ),
        ),
        migrations.AlterField(
            model_name="itemaddon",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="itemchoice",
            name="price_adjustment",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="available_addons",
            field=models.ManyToManyField(
                blank=True, related_name="menu_items", to="menu.itemaddon"
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="available_choices",
            field=models.ManyToManyField(
                blank=True, related_name="menu_items", to="menu.itemchoice"
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="has_choices",
            field=models.BooleanField(
                default=False,
                help_text="Item has different choices (e.g., meat type, size)",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="ingredients",
            field=models.TextField(blank=True, help_text="List main ingredients"),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["category", "is_available"],
                name="menu_menuit_categor_ed897a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["is_featured", "is_available"],
                name="menu_menuit_is_feat_95356a_idx",
            ),
        ),
    ]
