# Generated by Django 4.2.17 on 2024-12-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Cash on Delivery"), ("card", "Card Payment")],
                default="cash",
                max_length=20,
            ),
        ),
    ]
