# Generated by Django 4.2.17 on 2025-01-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_alter_order_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="rewards_used",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
