# Generated by Django 4.2.17 on 2025-01-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_order_rewards_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="points_earned",
            field=models.IntegerField(default=0),
        ),
    ]
