# Generated by Django 4.2.17 on 2025-01-22 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0004_category_created_at_category_image_and_more"),
        ("orders", "0008_order_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="addons",
            field=models.ManyToManyField(blank=True, to="menu.itemaddon"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="choice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="menu.itemchoice",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="special_instructions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
